import sys
import os

# Add parent directory to path so python imports find app package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from app.db.session import SessionLocal
from app.models.lab import Lab


def seed_labs():
    db = SessionLocal()
    try:
        print("Cleaning up old labs...")
        db.query(Lab).delete()
        db.commit()

        labs_data = [
            # Git Course
            {
                "title": "Git Fundamentals",
                "slug": "git-fundamentals",
                "description": "Learn the primary concepts, staging area, commit snapshots, and repository management.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Git",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Branching & Merging",
                "slug": "git-branching-and-merging",
                "description": "Deploy isolated environments using pointers, merge branches, and resolve conflicts.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Git",
                "icon": "git-branch",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Advanced Git",
                "slug": "advanced-git",
                "description": "Optimize logs history utilizing stashes, reflog recoveries, tags, and custom settings.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Git",
                "icon": "zap",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Team Workflows",
                "slug": "team-workflows",
                "description": "Coordinate work across remote origins, sync branches, and resolve complex merge conflicts.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Git",
                "icon": "users",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Linux
            {
                "title": "Linux Command Line Basics",
                "slug": "linux-command-line-basics",
                "description": "Master files navigation, path routing, standard inputs/outputs, and piping commands.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Linux",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": False,
            },
            {
                "title": "Linux Permissions & Users",
                "slug": "linux-permissions-and-users",
                "description": "Learn how to manage files, groups, users, and modify access rules securely using chmod/chown.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Linux",
                "icon": "shield",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Bash Scripting Fundamentals",
                "slug": "bash-scripting-fundamentals",
                "description": "Learn conditional logic, looping structures, environment variables, and reusable functions in Bash.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Linux",
                "icon": "code",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Linux System Calls with strace",
                "slug": "linux-system-calls-with-strace",
                "description": "Debug process behaviors, identify locks, and trace kernel-level system calls using strace.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Linux",
                "icon": "activity",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Docker
            {
                "title": "Docker Fundamentals",
                "slug": "docker-fundamentals",
                "description": "Introduction to container runtimes, pull operations, port mapping, and volume configurations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Docker",
                "icon": "box",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Multi-Container with Docker Compose",
                "slug": "multi-container-with-docker-compose",
                "description": "Deploy a multi-tier database and web application stack locally using Docker Compose YAML properties.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "network",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Optimizing Dockerfiles",
                "slug": "optimizing-dockerfiles",
                "description": "Build high-security minimal containers utilizing multi-stage configurations and alpine base runtimes.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "zap",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Docker Networking Deep Dive",
                "slug": "docker-networking-deep-dive",
                "description": "Configure overlay networks, bridge adapter bindings, and investigate custom iptables routing.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "network",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Kubernetes Modular Courses
            {
                "title": "Kubernetes Fundamentals",
                "slug": "kubernetes-fundamentals",
                "description": "Learn the core components, control plane processes, and worker node architectures of Kubernetes.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "layers",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Pods",
                "slug": "kubernetes-pods",
                "description": "Deploy, inspect, and manage single and multi-container Pod workloads in Kubernetes namespaces.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "box",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Deployments",
                "slug": "kubernetes-deployments",
                "description": "Scale state-free container stacks, perform zero-downtime updates, and manage deployment rollbacks.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "layers",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "ReplicaSets",
                "slug": "kubernetes-replicasets",
                "description": "Understand how ReplicaSet controllers reconcile Pod instance counts automatically.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "refresh-cw",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Services",
                "slug": "kubernetes-services",
                "description": "Expose application pods using stable ClusterIP, NodePort, and LoadBalancer configurations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "share-2",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Namespaces",
                "slug": "kubernetes-namespaces",
                "description": "Organize and secure multiple independent project resources within the same Kubernetes cluster.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "grid",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "ConfigMaps",
                "slug": "kubernetes-configmaps",
                "description": "Decouple configurations variables from container images using ConfigMap stores.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "settings",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Secrets",
                "slug": "kubernetes-secrets",
                "description": "Inject token variables, API keys, and database passwords securely using Secret models.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "lock",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Persistent Volumes",
                "slug": "kubernetes-persistent-volumes",
                "description": "Define persistent cluster storage assets independent of individual Pod lifecycles.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "database",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Persistent Volume Claims",
                "slug": "kubernetes-persistent-volume-claims",
                "description": "Bind application resource requests dynamically to suitable Persistent Volumes.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "hard-drive",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Ingress",
                "slug": "kubernetes-ingress",
                "description": "Route external L7 HTTP/HTTPS traffic to internal services using ingress routing rules.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "globe",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Rolling Updates",
                "slug": "kubernetes-rolling-updates",
                "description": "Perform updates and configure maxSurge and maxUnavailable values for deployments.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "refresh-cw",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Jobs & CronJobs",
                "slug": "kubernetes-jobs-and-cronjobs",
                "description": "Run short-lived batch computations and schedule recurring cron tasks inside K8s.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "clock",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Resource Requests & Limits",
                "slug": "kubernetes-resource-requests-and-limits",
                "description": "Configure compute limits and requests to optimize CPU and RAM distribution models.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "activity",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Autoscaling (HPA)",
                "slug": "kubernetes-autoscaling-hpa",
                "description": "Scale deployment replicas dynamically based on real-time CPU utilization metrics.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "trending-up",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Helm Basics",
                "slug": "kubernetes-helm-basics",
                "description": "Install, upgrade, roll back, and package Kubernetes applications using Helm Charts.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "package",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Production Best Practices",
                "slug": "kubernetes-production-best-practices",
                "description": "Configure liveness probes, readiness endpoints, security contexts, and resource quotas.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "shield",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Capstone Project",
                "slug": "kubernetes-capstone-project",
                "description": "Deploy a complete multi-tier application stack with deployment modules, config sets, secrets, and PVCs.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Kubernetes",
                "icon": "award",
                "estimated_time": "90m",
                "status": "Active",
                "coming_soon": False,
            },
            # Terraform
            {
                "title": "Terraform Basics",
                "slug": "terraform-basics",
                "description": "Learn initializations, dry-run plans, applying configurations, and managing variables.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Terraform",
                "icon": "cpu",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "State Management in Terraform",
                "slug": "state-management-in-terraform",
                "description": "Understand lock mechanisms, workspace segregation, and migrating backends to remote stores.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Terraform",
                "icon": "lock",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "Designing Reusable Modules",
                "slug": "designing-reusable-modules",
                "description": "Author highly customizable infrastructure modules that scale across multiple environments.",
                "difficulty": "Advanced",
                "duration": "75 minutes",
                "category": "Terraform",
                "icon": "component",
                "estimated_time": "75m",
                "status": "Beta",
                "coming_soon": True,
            },
            # AWS
            {
                "title": "AWS S3 Storage Basics",
                "slug": "aws-s3-storage-basics",
                "description": "Configure object versioning, access control lists, and bucket lifecycle policies.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "cloud",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "IAM Users and Policies",
                "slug": "iam-users-and-policies",
                "description": "Configure user scopes, roles, groups, and authorize granular permissions using JSON templates.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "AWS",
                "icon": "key",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Multi-AZ VPC Setup",
                "slug": "multi-az-vpc-setup",
                "description": "Provision high-availability subnets, internet/NAT gateways, and custom route bindings.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "AWS",
                "icon": "network",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Jenkins
            {
                "title": "Jenkins Pipelines as Code",
                "slug": "jenkins-pipelines-as-code",
                "description": "Write and structure robust declarative Jenkinsfiles to execute multi-stage CI operations.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Jenkins",
                "icon": "workflow",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Jenkins Shared Libraries",
                "slug": "jenkins-shared-libraries",
                "description": "Write shared Groovy libraries to modularize and standardize CI workflows at scale.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Jenkins",
                "icon": "settings",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Ansible
            {
                "title": "Ansible Playbooks for Beginners",
                "slug": "ansible-playbooks-for-beginners",
                "description": "Write declarative Playbooks to manage system updates and package installations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Ansible",
                "icon": "book-open",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Ansible Roles & Galaxy",
                "slug": "ansible-roles-and-galaxy",
                "description": "Re-engineer tasks, handlers, vars, and templates into modular, reusable Ansible Roles.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Ansible",
                "icon": "layout",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },

            # GitHub Actions
            {
                "title": "GitHub Actions Fundamentals",
                "slug": "github-actions-fundamentals",
                "description": "Learn workflows configurations, job parallelisms, triggers, and runner environments.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "GitHub Actions",
                "icon": "play",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Building CI Pipelines",
                "slug": "building-ci-pipelines",
                "description": "Checkout code repositories, manage Node/Python setups, and run shell steps.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "GitHub Actions",
                "icon": "activity",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Testing & Artifact Management",
                "slug": "testing-and-artifact-management",
                "description": "Run tests and save output artifacts using upload-artifact actions.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "GitHub Actions",
                "icon": "archive",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Automated Deployments",
                "slug": "automated-deployments",
                "description": "Securely deploy release packages utilizing encrypted Secrets and environments.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "GitHub Actions",
                "icon": "send",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # CI/CD
            {
                "title": "Introduction to CI/CD",
                "slug": "introduction-to-cicd",
                "description": "Learn the software delivery lifecycle, pipelines, and manual vs automated delivery principles.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "CI/CD",
                "icon": "git-pull-request",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Continuous Integration",
                "slug": "continuous-integration",
                "description": "Automate code checks, syntax rules, compilation validation, and unit testing scripts.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "CI/CD",
                "icon": "activity",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Continuous Delivery",
                "slug": "continuous-delivery",
                "description": "Package build iterations and maintain package registry releases behind manual approval checkpoints.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "CI/CD",
                "icon": "archive",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Continuous Deployment",
                "slug": "continuous-deployment",
                "description": "Automate final staging and production deployment gates safely without manual triggers.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "CI/CD",
                "icon": "send",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Building a Complete CI/CD Pipeline",
                "slug": "building-a-complete-cicd-pipeline",
                "description": "Orchestrate complex pipelines combining compile gates, test scripts, approvals, and rollbacks.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "CI/CD",
                "icon": "refresh-cw",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Jenkins
            {
                "title": "Jenkins Fundamentals",
                "slug": "jenkins-fundamentals",
                "description": "Learn the main elements of Jenkins architecture including master, agent, and executors configurations.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Jenkins",
                "icon": "settings",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Installing & Configuring Jenkins",
                "slug": "installing-and-configuring-jenkins",
                "description": "Install, run, and secure a Jenkins controller environment with basic plugins.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Jenkins",
                "icon": "download-cloud",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Freestyle Jobs",
                "slug": "freestyle-jobs",
                "description": "Configure graphical linear build tasks, build triggers, and file collections properties.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Jenkins",
                "icon": "play",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Pipeline as Code (Jenkinsfile)",
                "slug": "pipeline-as-code-jenkinsfile",
                "description": "Learn to declare multi-stage build pipelines committed as text alongside code.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "file-text",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Declarative vs Scripted Pipelines",
                "slug": "declarative-vs-scripted-pipelines",
                "description": "Understand structured Declarative syntax and compare it to imperatively scripted Groovy node blocks.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "git-branch",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Distributed Builds & Agents",
                "slug": "distributed-builds-and-agents",
                "description": "Distribute resource compile execution pipelines across isolated agent pools via node labels.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "server",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Credentials & Secrets Management",
                "slug": "credentials-and-secrets-management",
                "description": "Safely bind database logins, API keys, and SSH keys in runtime variables environments.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "lock",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Plugins & Integrations",
                "slug": "plugins-and-integrations",
                "description": "Integrate third-party build status reports, Slack messaging webhooks, and git events hooks.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "cpu",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Building a Complete CI/CD Pipeline",
                "slug": "building-a-complete-cicd-pipeline-jenkins",
                "description": "Combine compilation steps, lint operations, automated unit tests, and final deployment rules.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Jenkins",
                "icon": "refresh-cw",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Jenkins Best Practices",
                "slug": "jenkins-best-practices",
                "description": "Configure log file pruning rules and backup server details to reduce master loads.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "check-square",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Jenkins Capstone Project",
                "slug": "jenkins-capstone-project",
                "description": "Deploy a multi-stage production deployment pipeline with artifacts archival and rollbacks.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Jenkins",
                "icon": "award",
                "estimated_time": "90m",
                "status": "Active",
                "coming_soon": False,
            },
            # Terraform
            {
                "title": "Terraform Fundamentals",
                "slug": "terraform-fundamentals",
                "description": "Learn HCL declarative syntax and initialize local workspaces.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "cpu",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Installing Terraform & Providers",
                "slug": "installing-terraform-and-providers",
                "description": "Understand registry provider configurations and resource plugins.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "download",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Variables, Outputs & Locals",
                "slug": "variables-outputs-and-locals",
                "description": "Customized parameter boundaries and local variables scope.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "settings",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Resources & Dependencies",
                "slug": "resources-and-dependencies",
                "description": "Configure explicit resource ordering and handle state graphs.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "git-commit",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "State Management",
                "slug": "state-management",
                "description": "Inspect tfstate cache structures and track active resources.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "database",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Modules",
                "slug": "modules",
                "description": "Import dry modular packages and scale infrastructure setups.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "layers",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Provisioners",
                "slug": "provisioners",
                "description": "Add local-exec bootstrap commands within resource components.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Workspaces",
                "slug": "workspaces",
                "description": "Isolate environment states using workspace CLI commands.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "monitor",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Remote State Concepts",
                "slug": "remote-state-concepts",
                "description": "Deploy backend state settings and check team lock files.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "cloud-lightning",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Best Practices",
                "slug": "best-practices-terraform",
                "description": "Incorporate style guide formatting and linting validations.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Terraform",
                "icon": "check-square",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Terraform Capstone Project",
                "slug": "terraform-capstone-project",
                "description": "Integrate multi-tier setups, inputs, and outputs validation checks.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Terraform",
                "icon": "award",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            # Ansible Course
            {
                "title": "Introduction to Ansible",
                "slug": "introduction-to-ansible",
                "description": "Learn the primary push-based configuration management concepts of Ansible.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "shield",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Inventory Files & Hosts",
                "slug": "inventory-files-and-hosts",
                "description": "Structure target host groups, INI properties, and connection variables.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "server",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Ad-hoc Commands",
                "slug": "ad-hoc-commands",
                "description": "Trigger quick module execution scripts directly on target node groupings.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Writing Playbooks",
                "slug": "writing-playbooks",
                "description": "Deploy stateful configuration states using structured YAML playbook definitions.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "code",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Variables & Facts",
                "slug": "variables-and-facts",
                "description": "Declare custom play variables and query dynamically gathered host system facts.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "database",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Templates & Jinja2",
                "slug": "templates-and-jinja2",
                "description": "Compile dynamic text configuration files using the Jinja2 rendering engine.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "file-text",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Roles",
                "slug": "roles",
                "description": "Organize tasks, templates, handlers, and variables into modular roles path structures.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "package",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Ansible Galaxy",
                "slug": "ansible-galaxy",
                "description": "Import and configure shared community roles utilizing Ansible Galaxy CLI.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "globe",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Tags, Handlers & Conditionals",
                "slug": "tags-handlers-and-conditionals",
                "description": "Incorporate task tags, conditional when blocks, and event notify handlers.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "git-commit",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Best Practices",
                "slug": "best-practices",
                "description": "Organize group_vars variable scopes and perform syntax validations.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Ansible",
                "icon": "check-square",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Ansible Capstone Project",
                "slug": "ansible-capstone-project",
                "description": "Deliver a complete multi-role web services automation deployment workflow.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Ansible",
                "icon": "award",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            # AWS Course
            {
                "title": "AWS Cloud Fundamentals",
                "slug": "aws-cloud-fundamentals",
                "description": "Learn the core global infrastructure, services, and CLI interface basics of AWS.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "shield",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "IAM Users, Groups & Roles",
                "slug": "iam-users-groups-and-roles",
                "description": "Configure administrative credentials, policy mappings, and user permissions securely.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "user",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "EC2 Virtual Machines",
                "slug": "ec2-virtual-machines",
                "description": "Launch elastic virtual compute instance servers and monitor setup logs.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "server",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "VPC Networking",
                "slug": "vpc-networking",
                "description": "Design isolated virtual networking boundaries, subnets, and routing adapters.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "activity",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "S3 Storage",
                "slug": "s3-storage",
                "description": "Manage object storage buckets, uploads, and lifecycle rules parameters.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "database",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "RDS Databases",
                "slug": "rds-databases",
                "description": "Deploy secure Postgres RDS database servers with automated configurations.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "database",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Load Balancers & Auto Scaling",
                "slug": "load-balancers-and-auto-scaling",
                "description": "Distribute incoming client workloads using ALB and scale virtual machine groups.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "bar-chart",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "CloudWatch Monitoring",
                "slug": "cloudwatch-monitoring",
                "description": "Monitor system resources metrics and define automated alarm thresholds.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "eye",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Infrastructure with Terraform on AWS",
                "slug": "infrastructure-with-terraform-on-aws",
                "description": "Provision AWS environments programmatically using declarative Terraform HCL manifests.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "cpu",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Deploying Applications on AWS",
                "slug": "deploying-applications-on-aws",
                "description": "Establish SSH server sessions and audit port bindings using curl utility.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "AWS Security Best Practices",
                "slug": "aws-security-best-practices",
                "description": "Restrict ports configurations using custom Security Group ingress firewall rules.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "shield",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "AWS Capstone Project",
                "slug": "aws-capstone-project",
                "description": "Deploy a complete multi-tier enterprise web application architecture on AWS.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "AWS",
                "icon": "award",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            # Azure Course
            {
                "title": "Azure Fundamentals",
                "slug": "azure-fundamentals",
                "description": "Learn the core global infrastructure, services, and CLI interface basics of Azure.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "shield",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Resource Groups",
                "slug": "azure-resource-groups",
                "description": "Manage logical container boundaries organizing Azure deployment lifecycles.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "folder",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Virtual Machines",
                "slug": "azure-virtual-machines",
                "description": "Launch scalable Virtual Machine compute nodes using Azure CLI.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "server",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Virtual Networks",
                "slug": "azure-virtual-networks",
                "description": "Design isolated virtual networking boundaries, subnets, and routing adapters.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "activity",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Storage Accounts & Blob Storage",
                "slug": "azure-storage-accounts-and-blob-storage",
                "description": "Manage object storage accounts, blob containers, and file uploads securely.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "database",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure SQL Database",
                "slug": "azure-sql-database",
                "description": "Deploy managed Azure SQL database servers with automated scaling and security.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "database",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Load Balancer & VM Scale Sets",
                "slug": "azure-load-balancer-and-vm-scale-sets",
                "description": "Distribute incoming client workloads using Load Balancer and scale VM pools.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "bar-chart",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Monitor",
                "slug": "azure-monitor",
                "description": "Monitor system resources telemetry parameters and configure automated alert rules.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "eye",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Infrastructure with Terraform on Azure",
                "slug": "infrastructure-with-terraform-on-azure",
                "description": "Provision Azure environments programmatically using declarative azurerm provider manifests.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "cpu",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Deploying Applications on Azure",
                "slug": "deploying-applications-on-azure",
                "description": "Establish SSH server sessions and audit port bindings using curl utility.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Security Best Practices",
                "slug": "azure-security-best-practices",
                "description": "Restrict ports configurations using Network Security Group ingress firewall rules.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Azure",
                "icon": "shield",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Azure Capstone Project",
                "slug": "azure-capstone-project",
                "description": "Deploy a complete multi-tier enterprise web application architecture on Azure.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Azure",
                "icon": "award",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            # Monitoring Course
            {
                "title": "Monitoring Fundamentals",
                "slug": "monitoring-fundamentals",
                "description": "Learn core observability pillars (Metrics, Logs, Traces) and SLA/SLO/SLI measurement basics.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "activity",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Prometheus Basics",
                "slug": "prometheus-basics",
                "description": "Configure Prometheus server scrape targets, TSDB storage engine, and command line tools.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "server",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "PromQL Queries",
                "slug": "promql-queries",
                "description": "Write PromQL expressions to filter time series metrics, calculate rates, and aggregate data.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Exporters & Metrics Collection",
                "slug": "exporters-and-metrics-collection",
                "description": "Instrument Linux hosts and application services using Node Exporter and custom metrics libraries.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "download-cloud",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Alertmanager",
                "slug": "alertmanager",
                "description": "Configure Alertmanager routing trees, silences, grouping, and notification channels.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "bell",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Grafana Dashboards",
                "slug": "grafana-dashboards",
                "description": "Build interactive Grafana dashboards, configure Prometheus data sources, panels, and variables.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "eye",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Monitoring Kubernetes",
                "slug": "monitoring-kubernetes",
                "description": "Monitor Kubernetes clusters using Prometheus Operator, kube-state-metrics, and Node Problem Detector.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "layers",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Monitoring Docker",
                "slug": "monitoring-docker",
                "description": "Track Docker container resource usage using cAdvisor metrics collector.",
                "difficulty": "Intermediate",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "box",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Monitoring Best Practices",
                "slug": "monitoring-best-practices",
                "description": "Adopt monitoring best practices, recording rules, alert thresholds tuning, and alerting hygiene.",
                "difficulty": "Advanced",
                "duration": "30 minutes",
                "category": "Monitoring",
                "icon": "check-square",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Monitoring Capstone Project",
                "slug": "monitoring-capstone-project",
                "description": "Orchestrate a complete production monitoring stack with Prometheus, Grafana, Alertmanager, and Node Exporter.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Monitoring",
                "icon": "award",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            # Observability
            {
                "title": "Log Aggregation with ELK",
                "slug": "log-aggregation-with-elk",
                "description": "Collect, index, and visualize application logs using Elasticsearch, Logstash, and Kibana.",
                "difficulty": "Intermediate",
                "duration": "75 minutes",
                "category": "Observability",
                "icon": "search",
                "estimated_time": "75m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Distributed Tracing with Jaeger",
                "slug": "distributed-tracing-with-jaeger",
                "description": "Trace request lifetimes across multi-service deployments using open telemetry tracing.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Observability",
                "icon": "activity",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
        ]

        print("Seeding labs...")
        for lab_data in labs_data:
            lab = Lab(**lab_data)
            db.add(lab)

        db.commit()
        print(f"Successfully seeded {len(labs_data)} labs!")

    except Exception as e:
        db.rollback()
        print(f"An error occurred while seeding: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    seed_labs()
