import sys
import os

# Add parent directory to path so python imports find app package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from app.db.session import SessionLocal
from app.models.lab import Lab


def seed_labs():
    db = SessionLocal()
    try:
        print("Cleaning up old labs...")
        db.query(Lab).delete()
        db.commit()

        labs_data = [
            # Git Course
            {
                "title": "Git Fundamentals",
                "slug": "git-fundamentals",
                "description": "Learn the primary concepts, staging area, commit snapshots, and repository management.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Git",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Branching & Merging",
                "slug": "git-branching-and-merging",
                "description": "Deploy isolated environments using pointers, merge branches, and resolve conflicts.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Git",
                "icon": "git-branch",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Advanced Git",
                "slug": "advanced-git",
                "description": "Optimize logs history utilizing stashes, reflog recoveries, tags, and custom settings.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Git",
                "icon": "zap",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Team Workflows",
                "slug": "team-workflows",
                "description": "Coordinate work across remote origins, sync branches, and resolve complex merge conflicts.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Git",
                "icon": "users",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Linux
            {
                "title": "Linux Command Line Basics",
                "slug": "linux-command-line-basics",
                "description": "Master files navigation, path routing, standard inputs/outputs, and piping commands.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Linux",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": False,
            },
            {
                "title": "Linux Permissions & Users",
                "slug": "linux-permissions-and-users",
                "description": "Learn how to manage files, groups, users, and modify access rules securely using chmod/chown.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Linux",
                "icon": "shield",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Bash Scripting Fundamentals",
                "slug": "bash-scripting-fundamentals",
                "description": "Learn conditional logic, looping structures, environment variables, and reusable functions in Bash.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Linux",
                "icon": "code",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Linux System Calls with strace",
                "slug": "linux-system-calls-with-strace",
                "description": "Debug process behaviors, identify locks, and trace kernel-level system calls using strace.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Linux",
                "icon": "activity",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Docker
            {
                "title": "Docker Fundamentals",
                "slug": "docker-fundamentals",
                "description": "Introduction to container runtimes, pull operations, port mapping, and volume configurations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Docker",
                "icon": "box",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Multi-Container with Docker Compose",
                "slug": "multi-container-with-docker-compose",
                "description": "Deploy a multi-tier database and web application stack locally using Docker Compose YAML properties.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "network",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Optimizing Dockerfiles",
                "slug": "optimizing-dockerfiles",
                "description": "Build high-security minimal containers utilizing multi-stage configurations and alpine base runtimes.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "zap",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Docker Networking Deep Dive",
                "slug": "docker-networking-deep-dive",
                "description": "Configure overlay networks, bridge adapter bindings, and investigate custom iptables routing.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "network",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Kubernetes Modular Courses
            {
                "title": "Kubernetes Fundamentals",
                "slug": "kubernetes-fundamentals",
                "description": "Learn the core components, control plane processes, and worker node architectures of Kubernetes.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "layers",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Pods",
                "slug": "kubernetes-pods",
                "description": "Deploy, inspect, and manage single and multi-container Pod workloads in Kubernetes namespaces.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "box",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Deployments",
                "slug": "kubernetes-deployments",
                "description": "Scale state-free container stacks, perform zero-downtime updates, and manage deployment rollbacks.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "layers",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "ReplicaSets",
                "slug": "kubernetes-replicasets",
                "description": "Understand how ReplicaSet controllers reconcile Pod instance counts automatically.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "refresh-cw",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Services",
                "slug": "kubernetes-services",
                "description": "Expose application pods using stable ClusterIP, NodePort, and LoadBalancer configurations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "share-2",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Namespaces",
                "slug": "kubernetes-namespaces",
                "description": "Organize and secure multiple independent project resources within the same Kubernetes cluster.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "grid",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "ConfigMaps",
                "slug": "kubernetes-configmaps",
                "description": "Decouple configurations variables from container images using ConfigMap stores.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "settings",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Secrets",
                "slug": "kubernetes-secrets",
                "description": "Inject token variables, API keys, and database passwords securely using Secret models.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "lock",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Persistent Volumes",
                "slug": "kubernetes-persistent-volumes",
                "description": "Define persistent cluster storage assets independent of individual Pod lifecycles.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "database",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Persistent Volume Claims",
                "slug": "kubernetes-persistent-volume-claims",
                "description": "Bind application resource requests dynamically to suitable Persistent Volumes.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "hard-drive",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Ingress",
                "slug": "kubernetes-ingress",
                "description": "Route external L7 HTTP/HTTPS traffic to internal services using ingress routing rules.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "globe",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Rolling Updates",
                "slug": "kubernetes-rolling-updates",
                "description": "Perform updates and configure maxSurge and maxUnavailable values for deployments.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "refresh-cw",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Jobs & CronJobs",
                "slug": "kubernetes-jobs-and-cronjobs",
                "description": "Run short-lived batch computations and schedule recurring cron tasks inside K8s.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "clock",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Resource Requests & Limits",
                "slug": "kubernetes-resource-requests-and-limits",
                "description": "Configure compute limits and requests to optimize CPU and RAM distribution models.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "activity",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Autoscaling (HPA)",
                "slug": "kubernetes-autoscaling-hpa",
                "description": "Scale deployment replicas dynamically based on real-time CPU utilization metrics.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "trending-up",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Helm Basics",
                "slug": "kubernetes-helm-basics",
                "description": "Install, upgrade, roll back, and package Kubernetes applications using Helm Charts.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "package",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Production Best Practices",
                "slug": "kubernetes-production-best-practices",
                "description": "Configure liveness probes, readiness endpoints, security contexts, and resource quotas.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "shield",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Capstone Project",
                "slug": "kubernetes-capstone-project",
                "description": "Deploy a complete multi-tier application stack with deployment modules, config sets, secrets, and PVCs.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Kubernetes",
                "icon": "award",
                "estimated_time": "90m",
                "status": "Active",
                "coming_soon": False,
            },
            # Terraform
            {
                "title": "Terraform Basics",
                "slug": "terraform-basics",
                "description": "Learn initializations, dry-run plans, applying configurations, and managing variables.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Terraform",
                "icon": "cpu",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "State Management in Terraform",
                "slug": "state-management-in-terraform",
                "description": "Understand lock mechanisms, workspace segregation, and migrating backends to remote stores.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Terraform",
                "icon": "lock",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "Designing Reusable Modules",
                "slug": "designing-reusable-modules",
                "description": "Author highly customizable infrastructure modules that scale across multiple environments.",
                "difficulty": "Advanced",
                "duration": "75 minutes",
                "category": "Terraform",
                "icon": "component",
                "estimated_time": "75m",
                "status": "Beta",
                "coming_soon": True,
            },
            # AWS
            {
                "title": "AWS S3 Storage Basics",
                "slug": "aws-s3-storage-basics",
                "description": "Configure object versioning, access control lists, and bucket lifecycle policies.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "cloud",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "IAM Users and Policies",
                "slug": "iam-users-and-policies",
                "description": "Configure user scopes, roles, groups, and authorize granular permissions using JSON templates.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "AWS",
                "icon": "key",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Multi-AZ VPC Setup",
                "slug": "multi-az-vpc-setup",
                "description": "Provision high-availability subnets, internet/NAT gateways, and custom route bindings.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "AWS",
                "icon": "network",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Azure
            {
                "title": "Azure Virtual Machines",
                "slug": "azure-virtual-machines",
                "description": "Provision Linux Virtual Machines on Azure and establish secure ssh keys associations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Azure",
                "icon": "server",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Azure Blob Storage Configuration",
                "slug": "azure-blob-storage-configuration",
                "description": "Deploy blob storage containers, customize access tiers, and authorize access using SAS tokens.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Azure",
                "icon": "hard-drive",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Jenkins
            {
                "title": "Jenkins Pipelines as Code",
                "slug": "jenkins-pipelines-as-code",
                "description": "Write and structure robust declarative Jenkinsfiles to execute multi-stage CI operations.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Jenkins",
                "icon": "workflow",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Jenkins Shared Libraries",
                "slug": "jenkins-shared-libraries",
                "description": "Write shared Groovy libraries to modularize and standardize CI workflows at scale.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Jenkins",
                "icon": "settings",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Ansible
            {
                "title": "Ansible Playbooks for Beginners",
                "slug": "ansible-playbooks-for-beginners",
                "description": "Write declarative Playbooks to manage system updates and package installations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Ansible",
                "icon": "book-open",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Ansible Roles & Galaxy",
                "slug": "ansible-roles-and-galaxy",
                "description": "Re-engineer tasks, handlers, vars, and templates into modular, reusable Ansible Roles.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Ansible",
                "icon": "layout",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },

            # GitHub Actions
            {
                "title": "GitHub Actions Fundamentals",
                "slug": "github-actions-fundamentals",
                "description": "Learn workflows configurations, job parallelisms, triggers, and runner environments.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "GitHub Actions",
                "icon": "play",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Building CI Pipelines",
                "slug": "building-ci-pipelines",
                "description": "Checkout code repositories, manage Node/Python setups, and run shell steps.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "GitHub Actions",
                "icon": "activity",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Testing & Artifact Management",
                "slug": "testing-and-artifact-management",
                "description": "Run tests and save output artifacts using upload-artifact actions.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "GitHub Actions",
                "icon": "archive",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Automated Deployments",
                "slug": "automated-deployments",
                "description": "Securely deploy release packages utilizing encrypted Secrets and environments.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "GitHub Actions",
                "icon": "send",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # CI/CD
            {
                "title": "Introduction to CI/CD",
                "slug": "introduction-to-cicd",
                "description": "Learn the software delivery lifecycle, pipelines, and manual vs automated delivery principles.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "CI/CD",
                "icon": "git-pull-request",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Continuous Integration",
                "slug": "continuous-integration",
                "description": "Automate code checks, syntax rules, compilation validation, and unit testing scripts.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "CI/CD",
                "icon": "activity",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Continuous Delivery",
                "slug": "continuous-delivery",
                "description": "Package build iterations and maintain package registry releases behind manual approval checkpoints.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "CI/CD",
                "icon": "archive",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Continuous Deployment",
                "slug": "continuous-deployment",
                "description": "Automate final staging and production deployment gates safely without manual triggers.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "CI/CD",
                "icon": "send",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Building a Complete CI/CD Pipeline",
                "slug": "building-a-complete-cicd-pipeline",
                "description": "Orchestrate complex pipelines combining compile gates, test scripts, approvals, and rollbacks.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "CI/CD",
                "icon": "refresh-cw",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Jenkins
            {
                "title": "Jenkins Fundamentals",
                "slug": "jenkins-fundamentals",
                "description": "Learn the main elements of Jenkins architecture including master, agent, and executors configurations.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Jenkins",
                "icon": "settings",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Installing & Configuring Jenkins",
                "slug": "installing-and-configuring-jenkins",
                "description": "Install, run, and secure a Jenkins controller environment with basic plugins.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Jenkins",
                "icon": "download-cloud",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Freestyle Jobs",
                "slug": "freestyle-jobs",
                "description": "Configure graphical linear build tasks, build triggers, and file collections properties.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Jenkins",
                "icon": "play",
                "estimated_time": "30m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Pipeline as Code (Jenkinsfile)",
                "slug": "pipeline-as-code-jenkinsfile",
                "description": "Learn to declare multi-stage build pipelines committed as text alongside code.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "file-text",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Declarative vs Scripted Pipelines",
                "slug": "declarative-vs-scripted-pipelines",
                "description": "Understand structured Declarative syntax and compare it to imperatively scripted Groovy node blocks.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "git-branch",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Distributed Builds & Agents",
                "slug": "distributed-builds-and-agents",
                "description": "Distribute resource compile execution pipelines across isolated agent pools via node labels.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "server",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Credentials & Secrets Management",
                "slug": "credentials-and-secrets-management",
                "description": "Safely bind database logins, API keys, and SSH keys in runtime variables environments.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "lock",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Plugins & Integrations",
                "slug": "plugins-and-integrations",
                "description": "Integrate third-party build status reports, Slack messaging webhooks, and git events hooks.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "cpu",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Building a Complete CI/CD Pipeline",
                "slug": "building-a-complete-cicd-pipeline-jenkins",
                "description": "Combine compilation steps, lint operations, automated unit tests, and final deployment rules.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Jenkins",
                "icon": "refresh-cw",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Jenkins Best Practices",
                "slug": "jenkins-best-practices",
                "description": "Configure log file pruning rules and backup server details to reduce master loads.",
                "difficulty": "Advanced",
                "duration": "45 minutes",
                "category": "Jenkins",
                "icon": "check-square",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Jenkins Capstone Project",
                "slug": "jenkins-capstone-project",
                "description": "Deploy a multi-stage production deployment pipeline with artifacts archival and rollbacks.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Jenkins",
                "icon": "award",
                "estimated_time": "90m",
                "status": "Active",
                "coming_soon": False,
            },
            # Monitoring
            {
                "title": "Prometheus Basics",
                "slug": "prometheus-basics",
                "description": "Scrape node metrics and write basic PromQL syntax to review system indicators.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Monitoring",
                "icon": "bar-chart",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Grafana Visualization",
                "slug": "grafana-visualization",
                "description": "Author telemetry dashboards using Prometheus metrics and define dynamic alert hooks.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Monitoring",
                "icon": "eye",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Observability
            {
                "title": "Log Aggregation with ELK",
                "slug": "log-aggregation-with-elk",
                "description": "Collect, index, and visualize application logs using Elasticsearch, Logstash, and Kibana.",
                "difficulty": "Intermediate",
                "duration": "75 minutes",
                "category": "Observability",
                "icon": "search",
                "estimated_time": "75m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Distributed Tracing with Jaeger",
                "slug": "distributed-tracing-with-jaeger",
                "description": "Trace request lifetimes across multi-service deployments using open telemetry tracing.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Observability",
                "icon": "activity",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
        ]

        print("Seeding labs...")
        for lab_data in labs_data:
            lab = Lab(**lab_data)
            db.add(lab)

        db.commit()
        print(f"Successfully seeded {len(labs_data)} labs!")

    except Exception as e:
        db.rollback()
        print(f"An error occurred while seeding: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    seed_labs()
