import sys
import os

# Add parent directory to path so python imports find app package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from app.db.session import SessionLocal
from app.models.lab import Lab


def seed_labs():
    db = SessionLocal()
    try:
        print("Cleaning up old labs...")
        db.query(Lab).delete()
        db.commit()

        labs_data = [
            # Linux
            {
                "title": "Linux Command Line Basics",
                "slug": "linux-command-line-basics",
                "description": "Master files navigation, path routing, standard inputs/outputs, and piping commands.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Linux",
                "icon": "terminal",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": False,
            },
            {
                "title": "Linux Permissions & Users",
                "slug": "linux-permissions-and-users",
                "description": "Learn how to manage files, groups, users, and modify access rules securely using chmod/chown.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Linux",
                "icon": "shield",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Bash Scripting Fundamentals",
                "slug": "bash-scripting-fundamentals",
                "description": "Learn conditional logic, looping structures, environment variables, and reusable functions in Bash.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Linux",
                "icon": "code",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Linux System Calls with strace",
                "slug": "linux-system-calls-with-strace",
                "description": "Debug process behaviors, identify locks, and trace kernel-level system calls using strace.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Linux",
                "icon": "activity",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Docker
            {
                "title": "Docker Fundamentals",
                "slug": "docker-fundamentals",
                "description": "Introduction to container runtimes, pull operations, port mapping, and volume configurations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Docker",
                "icon": "box",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Multi-Container with Docker Compose",
                "slug": "multi-container-with-docker-compose",
                "description": "Deploy a multi-tier database and web application stack locally using Docker Compose YAML properties.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "network",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Optimizing Dockerfiles",
                "slug": "optimizing-dockerfiles",
                "description": "Build high-security minimal containers utilizing multi-stage configurations and alpine base runtimes.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "zap",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            {
                "title": "Docker Networking Deep Dive",
                "slug": "docker-networking-deep-dive",
                "description": "Configure overlay networks, bridge adapter bindings, and investigate custom iptables routing.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Docker",
                "icon": "network",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": False,
            },
            # Kubernetes
            {
                "title": "Kubernetes Pods & Deployments",
                "slug": "kubernetes-pods-and-deployments",
                "description": "Deploy pods, manage replica counts, and perform rolling updates with custom YAML configurations.",
                "difficulty": "Beginner",
                "duration": "60 minutes",
                "category": "Kubernetes",
                "icon": "layers",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "K8s ConfigMaps & Secrets",
                "slug": "k8s-configmaps-and-secrets",
                "description": "Inject config maps and secure base64 secret credentials into live running containers.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Kubernetes",
                "icon": "lock",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Kubernetes Services & Networking",
                "slug": "kubernetes-services-and-networking",
                "description": "Expose container endpoints to internal and external networks using NodePort and Ingress controllers.",
                "difficulty": "Intermediate",
                "duration": "75 minutes",
                "category": "Kubernetes",
                "icon": "globe",
                "estimated_time": "75m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "Managing State with PVCs",
                "slug": "managing-state-with-pvcs",
                "description": "Configure persistent storage volumes, claims, and storage classes inside single-node clusters.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Kubernetes",
                "icon": "database",
                "estimated_time": "90m",
                "status": "Active",
                "coming_soon": True,
            },
            # Terraform
            {
                "title": "Terraform Basics",
                "slug": "terraform-basics",
                "description": "Learn initializations, dry-run plans, applying configurations, and managing variables.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Terraform",
                "icon": "cpu",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "State Management in Terraform",
                "slug": "state-management-in-terraform",
                "description": "Understand lock mechanisms, workspace segregation, and migrating backends to remote stores.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Terraform",
                "icon": "lock",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "Designing Reusable Modules",
                "slug": "designing-reusable-modules",
                "description": "Author highly customizable infrastructure modules that scale across multiple environments.",
                "difficulty": "Advanced",
                "duration": "75 minutes",
                "category": "Terraform",
                "icon": "component",
                "estimated_time": "75m",
                "status": "Beta",
                "coming_soon": True,
            },
            # AWS
            {
                "title": "AWS S3 Storage Basics",
                "slug": "aws-s3-storage-basics",
                "description": "Configure object versioning, access control lists, and bucket lifecycle policies.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "AWS",
                "icon": "cloud",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "IAM Users and Policies",
                "slug": "iam-users-and-policies",
                "description": "Configure user scopes, roles, groups, and authorize granular permissions using JSON templates.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "AWS",
                "icon": "key",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Multi-AZ VPC Setup",
                "slug": "multi-az-vpc-setup",
                "description": "Provision high-availability subnets, internet/NAT gateways, and custom route bindings.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "AWS",
                "icon": "network",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Azure
            {
                "title": "Azure Virtual Machines",
                "slug": "azure-virtual-machines",
                "description": "Provision Linux Virtual Machines on Azure and establish secure ssh keys associations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Azure",
                "icon": "server",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Azure Blob Storage Configuration",
                "slug": "azure-blob-storage-configuration",
                "description": "Deploy blob storage containers, customize access tiers, and authorize access using SAS tokens.",
                "difficulty": "Intermediate",
                "duration": "45 minutes",
                "category": "Azure",
                "icon": "hard-drive",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Jenkins
            {
                "title": "Jenkins Pipelines as Code",
                "slug": "jenkins-pipelines-as-code",
                "description": "Write and structure robust declarative Jenkinsfiles to execute multi-stage CI operations.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Jenkins",
                "icon": "workflow",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Jenkins Shared Libraries",
                "slug": "jenkins-shared-libraries",
                "description": "Write shared Groovy libraries to modularize and standardize CI workflows at scale.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Jenkins",
                "icon": "settings",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Ansible
            {
                "title": "Ansible Playbooks for Beginners",
                "slug": "ansible-playbooks-for-beginners",
                "description": "Write declarative Playbooks to manage system updates and package installations.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Ansible",
                "icon": "book-open",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Ansible Roles & Galaxy",
                "slug": "ansible-roles-and-galaxy",
                "description": "Re-engineer tasks, handlers, vars, and templates into modular, reusable Ansible Roles.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Ansible",
                "icon": "layout",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Git
            {
                "title": "Git Branching & Merging",
                "slug": "git-branching-and-merging",
                "description": "Understand commits, check out references, merge branches, and resolve conflicts.",
                "difficulty": "Beginner",
                "duration": "30 minutes",
                "category": "Git",
                "icon": "git-branch",
                "estimated_time": "30m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Advanced Git Workflows",
                "slug": "advanced-git-workflows",
                "description": "Clean project histories utilizing interactive rebase, squash commits, and reflog recoveries.",
                "difficulty": "Advanced",
                "duration": "60 minutes",
                "category": "Git",
                "icon": "shuffle",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            # GitHub Actions
            {
                "title": "CI Pipelines with GitHub Actions",
                "slug": "ci-pipelines-with-github-actions",
                "description": "Author automated CI runs triggered on push actions to parse code structure and execute tests.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "GitHub Actions",
                "icon": "play",
                "estimated_time": "45m",
                "status": "Active",
                "coming_soon": True,
            },
            {
                "title": "Automated Deployments",
                "slug": "automated-deployments",
                "description": "Deliver built container assets to cloud container registries using secure GitHub Secrets.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "GitHub Actions",
                "icon": "send",
                "estimated_time": "60m",
                "status": "Active",
                "coming_soon": True,
            },
            # Monitoring
            {
                "title": "Prometheus Basics",
                "slug": "prometheus-basics",
                "description": "Scrape node metrics and write basic PromQL syntax to review system indicators.",
                "difficulty": "Intermediate",
                "duration": "60 minutes",
                "category": "Monitoring",
                "icon": "bar-chart",
                "estimated_time": "60m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Grafana Visualization",
                "slug": "grafana-visualization",
                "description": "Author telemetry dashboards using Prometheus metrics and define dynamic alert hooks.",
                "difficulty": "Beginner",
                "duration": "45 minutes",
                "category": "Monitoring",
                "icon": "eye",
                "estimated_time": "45m",
                "status": "Beta",
                "coming_soon": True,
            },
            # Observability
            {
                "title": "Log Aggregation with ELK",
                "slug": "log-aggregation-with-elk",
                "description": "Collect, index, and visualize application logs using Elasticsearch, Logstash, and Kibana.",
                "difficulty": "Intermediate",
                "duration": "75 minutes",
                "category": "Observability",
                "icon": "search",
                "estimated_time": "75m",
                "status": "Beta",
                "coming_soon": True,
            },
            {
                "title": "Distributed Tracing with Jaeger",
                "slug": "distributed-tracing-with-jaeger",
                "description": "Trace request lifetimes across multi-service deployments using open telemetry tracing.",
                "difficulty": "Advanced",
                "duration": "90 minutes",
                "category": "Observability",
                "icon": "activity",
                "estimated_time": "90m",
                "status": "Beta",
                "coming_soon": True,
            },
        ]

        print("Seeding labs...")
        for lab_data in labs_data:
            lab = Lab(**lab_data)
            db.add(lab)

        db.commit()
        print(f"Successfully seeded {len(labs_data)} labs!")

    except Exception as e:
        db.rollback()
        print(f"An error occurred while seeding: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    seed_labs()
